### ISSUE TITLE
Amazon search no longer working for me

### ISSUE THREAD

**Issue by samedney** [Exeu/Amazon-ECS-PHP-Library#10]
I have just come back to doing some work on this project, and for some reason the Amazon product search is no longer working for me. I'm not sure when it stopped working as I very rarely check the site - but want to start developing it some more now...

Im trying:

require 'lib/AmazonECS.class.php';

//declare the amazong ECS class $amazonEcs = new AmazonECS(AWS_API_KEY, AWS_API_SECRET_KEY, 'UK', AWS_ASSOCIATE_ID);

//tell the amazon class that we want an array, not an object $amazonEcs->setReturnType(AmazonECS::RETURN_TYPE_ARRAY);

//create the amazon object (array) $response = $amazonEcs->category($category)->responseGroup('Small,Images,Offers')->search($search); 

Currently, Im getting:

"We are unable to process your request at this time. Please retry your request."

As a response to running the API based search.

Any ideas as to why this might be?

Thanks,

Sam
ps. I really can not get formatting to work in these 'Issues' - apologies!

**Comment by Exeu** [comment]
I can't reproduce it. The class is still working fine.
All sample Files running correctly.

Maybe you could do an Update to the latest version of the class if you don't have it but this should not be the problem.

**Comment by samedney** [comment]
Seems to be working fine for me today too. I guess it was just a temporary thing with Amazon. Bad timing I guess! Thanks for checking anyway.
