### ISSUE TITLE
Amazon WSDL file not found - new location

### ISSUE THREAD

**Issue by wjgilmore** [Exeu/Amazon-ECS-PHP-Library#12]
Hi,

Attempting to run one of the sample files returns a fatal WSDL file not found error:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://ecs.amazonaws.com/AWSECommerceService/2010-11-01/EN/AWSECommerceService.wsdl' : failed to load external entity "http://ecs.amazonaws.com/AWSECommerceService/2010-11-01/EN/AWSECommerceService.wsdl" in /var/www/developer/2011/amazonpas/amazon/lib/AmazonECS.class.php:208

This is because http://ecs.amazonaws.com/AWSECommerceService/2010-11-01/EN/AWSECommerceService.wsdl does not exist (note I've set the language to EN).

I did some research and found this WSDL:

http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl

So I updated the $webserviceUri property in AmazonECS.class.php to the new WSDL URL and everything worked great. However notice this doesn't take into account the locality (EN, DE, etc), so I'm not 100% sure this is the correct URL and instead wonder whether this is just the default EN URL.

Hope this helps,
Jason

**Comment by Exeu** [comment]
Hi,
the Country-Code EN does not exists. 
What Countrys you could use you can see here: http://docs.amazonwebservices.com/AWSECommerceService/latest/DG/WSDLLocation.html

So try to use either UK instead of EN or US depending on the country you are currently running your service.
This parameter does not have to do something with the language more with the country database of the amazon Products you want to browse.

King regards,
Exeu

**Comment by wjgilmore** [comment]
Aha yes of course, my bad. Typing engaged before brain!

Thanks so much, the library works perfectly!

Jason

**Comment by akashbhikadiya3** [comment]
hello i gettting error like

"
[12-Jan-2016 09:14:46 Etc/GMT] PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl' : failed to load external entity "http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl"
 in /home/silverat/public_html/jcardz/AmazonECS_133/lib/AmazonECS.class.php on line 237

"

**Comment by briankirsten** [comment]
What version of PHP are you running? Maybe this is happening to you?

http://stackoverflow.com/questions/12875409/soap-php-fault-parsing-wsdl-failed-to-load-external-entity
