### ISSUE TITLE
Best price field

### ISSUE THREAD

**Issue by samedney** [Exeu/Amazon-ECS-PHP-Library#15]
How should I know which price field is the correct one to use? Is there a method for finding out which price Amazon are currently using? There are several in the results.

**Comment by samedney** [comment]
eg. If you look at this item: http://www.amazon.co.uk/gp/product/B000I5ZHYQ

The current price on Amazon is £1.15.

But even if I get large results, I don't seem to have that price available to me.

Is there a specific group I need to include?...

Many thanks.

**Comment by samedney** [comment]
Im currently using:
['Offers']['Offer']['OfferListing']['Price']['Amount'](if available)

Then:
['OfferSummary']['LowestNewPrice']['Amount']

But this isnt a reliable method, and sometimes results in some weird numbers.

**Comment by Exeu** [comment]
Hi,
there is no method to get the price in this class.
The only thing you can do here is to work with the result which directly comes from amazon.
I'm sorry but i have no idea in which field of the response the correct price is served.

Maybe the Documentation of Amazon could help.
Here are the Responsegroups described: http://docs.amazonwebservices.com/AWSECommerceService/latest/DG/index.html?CHAP_ResponseGroupsList.html

**Comment by samedney** [comment]
OK - If I work something out I will let you know. It might be a useful feature to add directly to the class. Thanks.

**Comment by Exeu** [comment]
Thanks!
You're right: it might be a usefull feature but this class is the wrong place for this.
It's only a "gateway" between amazon and your server :)
So the only thing for this class to do is: Request for some Data -> Return the Response.
If i start to implement features like this the next day someone else wants a like x :) 
So this class will grow and grwo and grow up to thousands of lines code.
Keep in mind that you can extend this class and implement your own features in your own class.
Another way to get the prices maye is to analyse the repsonse which a search request returns.

So you can write somthing like an Analyizer-Class which you can for example call like this:

$amazonEcs = new AmazonECS(AWS_API_KEY, AWS_API_SECRET_KEY, 'de', AWS_ASSOCIATE_TAG);
$response = $amazonEcs->category('DVD')->responseGroup('Large')->search("Matrix Revolutions");

$responseAnalyzer = new ResponseAnalyzer($response);
$responseAnalyzer->getPirce();

**Comment by samedney** [comment]
Yes, I agree. As things stand its a nice tidy class! These things have a 
habit of growing out of control so yes, lets not add it!

For now I have just added a check for several values when I parse the 
result set.

It works quite well and as I am only returning 10 items, its fast enough 
for what I need.

Once I have tidied up the code, I will add it to the wiki.

Thanks again for making my life a lot easier!

Sam

**Comment by samedney** [comment]
Also - reading through the forums on Amazon, it seems that lots of 
people have this problem.

What it seems is really needed is for Amazon to expose the value for the 
currently displayed price on the Amazon page.

Instead, what you need to do is run through all the offers, work out the 
'lowest new' price, check the RRP, look at used prices...

It is quite frustrating to open the link to the Amazon page and see a 
different price (as the default) to the one I was previously displaying. 
Apparently, this is also the case if you add items to the Cart.

**Comment by Exeu** [comment]
Thanks for these efforts!
What about opening a topic on the amazon dev forum?
If there are many people with the same problem there is maybe a chance to get this price value with the next version of the amazon webservice.
I totally agree that this is frustrating. If i see a price on a website for some product i want to buy this product for this price and for no other price.
For me its interesting why there issn't a real price value. Maybe it has to do with some law?
I don't know..
