### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by whoisstan** [Exeu/Amazon-ECS-PHP-Library#17]
Hey,

getting this message here:

"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details." 

I am using my 'Access Key ID' and my 'Secret Key'. I am using php5.3.6/apache 2.2.19 on OS X Lion. Am I lacking a signing library?

Thanks so much,
Stan

**Comment by whoisstan** [comment]
I uncommented some var_dump's in sampleItemSearch.php and now I see this:

SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://ecs.amazonaws.com/AWSECommerceService/2010-11-01/EN/AWSECommerceService.wsdl' : failed to load external entity "http://ecs.amazonaws.com/AWSECommerceService/2010-11-01/EN/AWSECommerceService.wsdl"

Is this helpful?

**Comment by Exeu** [comment]
Hi,

what Version of this class you are using?

**Comment by whoisstan** [comment]
I downloaded it yesterday!

**Comment by Exeu** [comment]
Please open the class. Look at the top of it where the Versionnumber is served.
This error seems to come from an older version.

**Comment by whoisstan** [comment]
i had version 1.2. thanks for the help, its working now. I am making an interface for this here http://whoisstan.tumblr.com/post/7350201293/buy-it-later-hybrid-stores and will use your php interface for Amazon.
