### ISSUE TITLE
Japanese, Italy,Chinese site

### ISSUE THREAD

**Issue by bert2002** [Exeu/Amazon-ECS-PHP-Library#18]
Hi,

the possibleLocation for Japan needs to be co.jp and it is possible to add "it" and "cn". 

Thanks 

bert2002

**Comment by Exeu** [comment]
Hi,
this issue should be fixed with Version 1.3.1
Its now released and you can download it.

Thanks

**Comment by bert2002** [comment]
awesome :) Thanks for the good work.
