### ISSUE TITLE
Question about search results

### ISSUE THREAD

**Issue by samedney** [Exeu/Amazon-ECS-PHP-Library#22]
I have a weird problem and Im not sure if it is Amazon or something Im doing wrong. I have a feeling it is related to differences in Keywords and Item Names...

My site allows the user to search for products, which are then listed in a table. They can then click on that item to view the full details on Amazon, or they can choose to 'Add to list'.

Adding to list copies the title (and price, URL etc) to a new record in their wish-list.

Then automatically (or whenever a user clicks on that item) we search Amazon again using the Title field - but the item does not always show up, even though it is word for word copied. It seems to need to be more vague.

The reason I do this is that users are able to free-type items in to their wish-list, and clicking on it has the same effect as using the initial search button.

Any ideas?

If you want to try this out - www.isitonyourlist.com (reg required).

**Comment by Exeu** [comment]
Hi,
i don't know whats going on there :/
It seems that the amazon Search does not handles some parts of the title information for some reason.
You can try this here: http://amazonecs.pixel-web.org with the title: The Complete Matrix Trilogy [Blu-ray] [1999][Region Free]

Leaving out "[1999][Region Free]" leads to a result.. Adding "[1999][Region Free]" leads to no result. But i don't know why.

If you want to recveive more information about the product itself you can additionally store the ASIN number an start a Item Lookup Request when you click on the item.
Maybe this could help?

**Comment by samedney** [comment]
I will have a think about how the site needs to work. It's not a huge problem, it's just really confusing - especially for the users.

I can not seem to work out the exact reasons as to why some words help and others dont... and others still block out results.

If there was a way of knowing which words had undesirable effects, I could just strip them out!

If I find anything useful, will post back here.

Do you mind if we leave this ticket open for a while to see if anyone else has any ideas?

**Comment by Exeu** [comment]
I think i can close this issue right now.
