### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by naoisegolden** [Exeu/Amazon-ECS-PHP-Library#24]
Tried on a Firefox 8.0.1 Mac OS X 1.7.2 to search in the ES shop... nothing showed up

**Comment by Exeu** [comment]
If tried it for example with "Matrix" and Dategory "DVD" -> it works fine.
So what exactly you typed in there?
Maybe there wasn't any result for your keyword

**Comment by naoisegolden** [comment]
Well I just tried "viaje" and "galaxy" with cattegory: all , country: es..
and nothing. blank page, no changes, after aparently loading browser.

USA ans DE do retrieve results (although all prices are kA or something
like that, i just closed the tab because FF was crashing...)

2011/12/2 Jan Eichhorn <
reply@reply.github.com

**Comment by Exeu** [comment]
It seems like this is the same issue reported here: https://github.com/Exeu/Amazon-ECS-PHP-Library/issues/25

so i will close this one
