### ISSUE TITLE
SSL connection required for SOAP authentication

### ISSUE THREAD

**Issue by MarcosBL** [Exeu/Amazon-ECS-PHP-Library#25]
Class returns randomly "SSL connection required for SOAP authentication", for the same exact query, aboyut 80% of times.

Have been doing some test and it seems it throw "SSL connection required for SOAP authentication" if i search the same thing more than once in a row. Is there some "Ask just once, cache, don't ask again" thing in the Amazon Web Service ?

The error isn't very descriptive... as i'm using https

**Comment by MarcosBL** [comment]
Testing the Demo website, i see the same exact problem, i've been able to query twice for **La llave de Sarah** , now it throws error 500:

http://amazonecs.pixel-web.org/search.php?q=La+Llave+De+Sarah&category=Books&country=es&page=1

**Comment by Exeu** [comment]
Hmm interesting.
It seems that this has sth. to do with the country (es).
There was a similar problem before this where only es was affected for some reason.
If you try this with de: (http://amazonecs.pixel-web.org/search.php?q=Test&category=Books&country=de&page=1) everything works fine.

I don't now why but it seems that there is a problem with the ES-Api on Amazon.
i will make a few tests later that day and give you feedback.

**Comment by MarcosBL** [comment]
Thank you very much @Exeu !

**Comment by ghost** [comment]
Hi,

@Exeu, have you found a solution for this issue?

**Comment by Exeu** [comment]
Hi,
no i've not found out anything.
It seems there is a problem dealing with the requests on the amazon side.
No other country makes problems here and there is nothing special with ES at all.
So i currently have absolute no idea from where this comes from.

**Comment by ghost** [comment]
Hi!

Is it possible that the problem has been fixed?

**Comment by ghost** [comment]
Hi,

The Spanish ECS API continues with errors. But, I've been doing tests and I've detected a wierd behaviour. 

When I execute this url http://www.yobui.com/amazonsearch.php?q=Apple, I see sometimes it works, but few seconds later, the same query, stops to work and shows the message: "SSL connection required for SOAP authentication.". 

Could be something with the timestamp used to build the signature? Because it seems the moment when I execute the program affects the result.

Thanks.

**Comment by Exeu** [comment]
I don't think that it depends on the signature.
The Signature it selfs is rebuild for every request.
Also the Signature does not contain any information about a SSL Connection.
If the Signature does not match there would be another message displayed.

Maybe we should open a thread at the Amazon Dev Forum?

**Comment by ghost** [comment]
The thread is already open: https://forums.aws.amazon.com/thread.jspa?threadID=81522&tstart=0

**Comment by Exeu** [comment]
Seems to be fixed
