### ISSUE TITLE
Fatal Error on Line 229 AmazonECS.class.php

### ISSUE THREAD

**Issue by KayBeSee** [Exeu/Amazon-ECS-PHP-Library#30]
Hey --

I am trying to setup this product advertising API on my site, but keep getting an error:

**Fatal error: Uncaught SoapFault exception: [aws:Client.InvalidClientTokenId] The AWS Access Key Id you provided does not exist in our records. in /home/kaybesee/public_html/amazon/lib/AmazonECS.class.php:229 Stack trace: #0 /home/kaybesee/public_html/amazon/lib/AmazonECS.class.php(229): SoapClient->__soapCall('ItemSearch', Array) #1 /home/kaybesee/public_html/amazon/lib/AmazonECS.class.php(115): AmazonECS->performSoapRequest('ItemSearch', Array) #2 /home/kaybesee/public_html/amazon/index.php(15): AmazonECS->search('PHP 5') #3 {main} thrown in /home/kaybesee/public_html/amazon/lib/AmazonECS.class.php on line 229**

I have input my Associate Key, Secret Key, and Associate Tag in SampleSettings.php and in sampleItemSearch.php and I still get this error.

Can you help me out?

**Comment by Exeu** [comment]
Hey,
please check your keys for your account.
Maybe you have entered the Access Key and the Secret Key in the wrong order?
How to get a valid Access Key you can read here:

http://docs.amazonwebservices.com/AWSECommerceService/2011-08-01/GSG/GettinganAWSAccessKeyID.html

**Comment by Exeu** [comment]
i will close now
