### ISSUE TITLE
Amazon ECS Class - The request must contain the parameter Signature Error

### ISSUE THREAD

**Issue by cookieplanter** [Exeu/Amazon-ECS-PHP-Library#31]
The Class was working perfectly until now. Now I get this error - "The request must contain the parameter Signature.".

Originally, I got an error "Request has expired. Timestamp date is 2012-02-19T02:02:28Z." I changed date on the buildSoapHeader function to 2011-08-01. Now I get the error "The request must contain the parameter Signature.".

Can you please help?

**Comment by Exeu** [comment]
duplicate

**Comment by cookieplanter** [comment]
Hi Jan, can you help with the error I am getting? Thanks in advance.

Krishna.

On Sun, Feb 19, 2012 at 4:10 PM, Jan Eichhorn <
reply@reply.github.com

**Comment by Exeu** [comment]
You can't manipulate the date which is provided with the soap header.
If you change the Date it will result in an error.
You need to provide the actual Date there!

So its important that your clock on your system is running correctly.
And never touch the date on this function. This will go wrong.

**Comment by cookieplanter** [comment]
Thanks for your email Jan. I am hosted on Godaddy .. and the script was
working fine until now. Also, the script works fine on my local development
environment. So I know its got something to do with the date.. But I can't
seem to figure out.

This is my server date - http://oyebazaar.com/today.php

and this is the script error - http://oyebazaar.com/whatever/img/index.php

Please help.

Thanks,
Krishna.

On Mon, Feb 20, 2012 at 3:41 PM, Jan Eichhorn <
reply@reply.github.com

**Comment by Exeu** [comment]
Request has expired. Timestamp date is 2012-02-20T11:41:22Z.

This indicates that the system clock on your machine is not adjusted correctly.

If i run this onto my machine (with correctly adjusted clock) i get
2012-02-20T12:00:48Z

And on your machine:
2012-02-20T11:45:45Z.

As you can see your system is living 15 Minutes in the past!
So you have to set up your system clock correctly! Then it will work.

**Comment by Exeu** [comment]
Is it working now?

**Comment by cookieplanter** [comment]
Yes it is sorry.. sorry for the delayed response - I was away. The problem
was in the server time. Thank you again for your support and a great
library.

Cheers.

On Wed, Feb 22, 2012 at 12:07 AM, Jan Eichhorn <
reply@reply.github.com
