### ISSUE TITLE
Amazon ECS Class - The request must contain the parameter Signature Error

### ISSUE THREAD

**Issue by cookieplanter** [Exeu/Amazon-ECS-PHP-Library#32]
The Class was working perfectly until now. Now I get this error - "The request must contain the parameter Signature.".

Originally, I got an error "Request has expired. Timestamp date is 2012-02-19T02:02:28Z." I changed date on the buildSoapHeader function to 2011-08-01. Now I get the error "The request must contain the parameter Signature.".

The version of  Amazon ECS Class is 1.3.3-Dev

Can you please help?

**Comment by Exeu** [comment]
duplicate
