### ISSUE TITLE
Changes in the Product Advertising API

### ISSUE THREAD

**Issue by sparkyfen** [Exeu/Amazon-ECS-PHP-Library#38]
As written on the Amazon forums, there are changes to how many requests can be made per second.
More information here:
https://affiliate-program.amazon.com/gp/advertising/api/detail/faq.html

What it means for this library:
When making requests for a product, if you make more than 1 per second (if you are not making any revenue), a SoapClient error exception occurs.
Something like this:
Fatal Error: Your account id XXXXX is been throttled.

To fix:
My personal fix was to sleep(1) after every lookup() call.

**Comment by Exeu** [comment]
Thanks for the hint!
I will have a look what changes will result for the class.
I think this part has to be configurable.

**Comment by Exeu** [comment]
This feature is now implemented by default in version 1.3.3
You can no enable the delay via $amazonECS->requestDelay(true);
