### ISSUE TITLE
Class 'SoapClient' not found in

### ISSUE THREAD

**Issue by sagarntimer** [Exeu/Amazon-ECS-PHP-Library#40]
Your code is awesome. It is working perfectly fine on local machine but on the server its give me 
Fatal error:  Class 'SoapClient' not found in.......

Can ya help me out with it

**Comment by Exeu** [comment]
It seems that you have not installed the php extension SOAP.
Please install it on your server: if it is an ubuntu/debian try apt-get install php-soap or apt-get install php5-soap

SOAP is required for this class. Without it it could not run.

http://de1.php.net/manual/en/book.soap.php
