### ISSUE TITLE
get bestsellers list

### ISSUE THREAD

**Issue by SergeC** [Exeu/Amazon-ECS-PHP-Library#41]
Hi, thank for a grate lib.

How can I get a list of bestsellers?

example url: http://www.amazon.com/Best-Sellers-Video-Games-Core-Game-Downloads/zgbs/videogames/979455011/ref=amb_link_363628502_5?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=center-1&pf_rd_r=0RG7GS3W02J5PD73J0RZ&pf_rd_t=101&pf_rd_p=1381593702&pf_rd_i=979455011

Thanks

**Comment by daemkl** [comment]
thats actually kind of easy:

$response = $amazonEcs->responseGroup('BrowseNodeInfo,TopSellers')->browseNodeLookup(569604);
var_dump($response);

add the browseNodeID to browseNodeLookup for which you want to get the top10 bestsellers for.

**Comment by Exeu** [comment]
can i close this one?
