### ISSUE TITLE
Amazon ECS record more than 10

### ISSUE THREAD

**Issue by muhammadraizahmad** [Exeu/Amazon-ECS-PHP-Library#47]
i want to know how we get record more than 10 let 20 record on each call? is there any parameter have to pass to optionalParameters ??? please help me

**Comment by btray77** [comment]
Use: ->page(#) 

Look at https://gist.github.com/Exeu/4674423 for an example.

Also:
http://docs.aws.amazon.com/AWSECommerceService/2011-08-01/DG/ItemSearch.html
says:
The ItemPage parameter enables you to return a specified page of results. The maximum ItemPage number that can be returned is 10. An error is returned if you try to access higher numbered pages. If you do not include ItemPage in your request, the first page will be returned by default. There can be up to ten items per page.

**Comment by Exeu** [comment]
The number of results is limited to ten for each page except the all category. there is a higher number of results.
so there is no way to return more than 10 items per request. you have to use the page parameter to fetch more.

**Comment by muhammadraizahmad** [comment]
@Exeu  thanks for helping....:)
