### ISSUE TITLE
Question: Changing page & Limting results

### ISSUE THREAD

**Issue by elistone** [Exeu/Amazon-ECS-PHP-Library#48]
Two questions.
1. What do you use to change the number of results per page as I can't find it I have tried to use:
   
   ```
     "TotalResults" => "20"
   ```
   
   But this is doing nothing.
2. Is there anything that can be done about going to a higher page than 10? 
   As:
   
   ```
    "ItemPage" => "20"
   ```
   
   Is limited to 10, is that just amazon stopping you from doing any more? or can you get around it?

**Comment by hotrush** [comment]
1) yeap. its unusful
2) impossible

**Comment by Exeu** [comment]
There is no parameter to set the number of results (see http://docs.aws.amazon.com/AWSECommerceService/2011-08-01/DG/ItemSearch.html).

The number of pages is limited to 10 (also documented at the link above).
