### ISSUE TITLE
Uncaught SoapFault exception

### ISSUE THREAD

**Issue by mahmoodsd2001** [Exeu/Amazon-ECS-PHP-Library#51]
Hello,

Please help. when i try to search product with one amazon account (ECS_API_KEY, ECS_API_SECRET_KEY, ECS_ASSOCIATE_TAG) it's work.
but now i am tring it with another amazon account, but I get this error:

Fatal error: Uncaught SoapFault exception: [aws:Server.InternalError] We encountered an internal error. Please try again. in application\third_party\amazon_ecs\AmazonECS.class.php:212 Stack trace: #0 application\third_party\amazon_ecs\AmazonECS.class.php(212): SoapClient->__soapCall('BrowseNodeLooku...', Array) #1 application\third_party\amazon_ecs\AmazonECS.class.php(132): AmazonECS->performSoapRequest('BrowseNodeLooku...', Array) #2 application\controllers\digger.php(97): AmazonECS->browseNodeLookup('166835011') #3 [internal function]: Digger->process() #4 system\core\CodeIgniter.php(359): call_user_func_array(Array, Array) #5 index.php(202): require_once('C:\xampp\htdocs...') #6 {main} thrown in application\third_party\amazon_ecs\AmazonECS.class.php on line 212

**Comment by jaimeguzman** [comment]
HI, can you paste your access_log suphp exec and maybe errorlog ?
I recently don't have any problem with the library

Regards

**Comment by mahmoodsd2001** [comment]
Hi Jamie,
I don't know what this suphp, i am excuting the code in xampp (windows).
But, the code work fine with one amazon configuration, but with the second didn't work and get error above!!

What do you think about this ?
I created new amazon account, and create access and secret key from here:
https://console.aws.amazon.com/iam/home#users

And create associate tag (Tracking ID) from here:
https://affiliate-program.amazon.com/

**Comment by jaimeguzman** [comment]
Well at first you have to be sure your ID from amazon console are rigth and second make some debug your code. I use this library for integrate with a Drupal CMS, but you use codeigniter. Do you have some function for trace more exactly the error, may be is some bad request that you produce a Internal error.

``` php
  /**
   * Prepares the responsegroups and returns them as array
   *
   * @return array|prepared responsegroups
   */
  protected function prepareResponseGroup()
  {
    if (false === strstr($this->responseConfig['responseGroup'], ','))
      return $this->responseConfig['responseGroup'];

    return explode(',', $this->responseConfig['responseGroup']);
  }
```

I recommend you, read again the examples and make some test every case, and if you have all ok with your keys, your only have problem with the code.

Regards

**Comment by mahmoodsd2001** [comment]
Hi Jamie,
I found the problem, it was in the ID's

Thank you :+1:
